"""upd datatype

Revision ID: 66247c2ba633
Revises: 4e246f1f1b29
Create Date: 2025-05-20 19:18:09.445458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66247c2ba633'
down_revision: Union[str, None] = '4e246f1f1b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_records', 'data_type',
               existing_type=postgresql.ENUM('SLEEP_SESSION_DATA', 'BLOOD_OXYGEN_DATA', 'HEART_RATE_RECORD', 'ACTIVE_CALORIES_BURNED_RECORD', 'BASAL_METABOLIC_RATE_RECORD', 'BLOOD_PRESSURE_RECORD', 'BODY_FAT_RECORD', 'BODY_TEMPERATURE_RECORD', 'BONE_MASS_RECORD', 'DISTANCE_RECORD', 'EXERCISE_SESSION_RECORD', 'HYDRATION_RECORD', 'SPEED_RECORD', 'STEPS_RECORD', 'TOTAL_CALORIES_BURNED_RECORD', 'WEIGHT_RECORD', 'BASAL_BODY_TEMPERATURE_RECORD', 'FLOORS_CLIMBED_RECORD', 'INTERMENSTRUAL_BLEEDING_RECORD', 'LEAN_BODY_MASS_RECORD', 'MENSTRUATION_FLOW_RECORD', 'NUTRITION_RECORD', 'POWER_RECORD', 'RESPIRATORY_RATE_RECORD', 'RESTING_HEART_RATE_RECORD', 'SKIN_TEMPERATURE_RECORD', name='data_type_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_raw_records_data_type', table_name='raw_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_raw_records_data_type', 'raw_records', ['data_type'], unique=False)
    op.alter_column('raw_records', 'data_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SLEEP_SESSION_DATA', 'BLOOD_OXYGEN_DATA', 'HEART_RATE_RECORD', 'ACTIVE_CALORIES_BURNED_RECORD', 'BASAL_METABOLIC_RATE_RECORD', 'BLOOD_PRESSURE_RECORD', 'BODY_FAT_RECORD', 'BODY_TEMPERATURE_RECORD', 'BONE_MASS_RECORD', 'DISTANCE_RECORD', 'EXERCISE_SESSION_RECORD', 'HYDRATION_RECORD', 'SPEED_RECORD', 'STEPS_RECORD', 'TOTAL_CALORIES_BURNED_RECORD', 'WEIGHT_RECORD', 'BASAL_BODY_TEMPERATURE_RECORD', 'FLOORS_CLIMBED_RECORD', 'INTERMENSTRUAL_BLEEDING_RECORD', 'LEAN_BODY_MASS_RECORD', 'MENSTRUATION_FLOW_RECORD', 'NUTRITION_RECORD', 'POWER_RECORD', 'RESPIRATORY_RATE_RECORD', 'RESTING_HEART_RATE_RECORD', 'SKIN_TEMPERATURE_RECORD', name='data_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
