"""fix

Revision ID: 7b398e8250a5
Revises: 4d456687a54b
Create Date: 2025-05-30 00:39:47.389584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b398e8250a5'
down_revision: Union[str, None] = '4d456687a54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('outliers_records_raw_record_id_key'), 'outliers_records', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('outliers_records_raw_record_id_key'), 'outliers_records', ['raw_record_id'])
    # ### end Alembic commands ###
