"""init

Revision ID: cf4ee23e4f73
Revises: 
Create Date: 2025-04-25 18:53:07.675821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4ee23e4f73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.Enum('SLEEP_SESSION_DATA', 'BLOOD_OXYGEN_DATA', 'HEART_RATE_RECORD', 'ACTIVE_CALORIES_BURNED_RECORD', 'BASAL_METABOLIC_RATE_RECORD', 'BLOOD_PRESSURE_RECORD', 'BODY_FAT_RECORD', 'BODY_TEMPERATURE_RECORD', 'BONE_MASS_RECORD', 'DISTANCE_RECORD', 'EXERCISE_SESSION_RECORD', 'HYDRATION_RECORD', 'SPEED_RECORD', 'STEPS_RECORD', 'TOTAL_CALORIES_BURNED_RECORD', 'WEIGHT_RECORD', 'BASAL_BODY_TEMPERATURE_RECORD', 'FLOORS_CLIMBED_RECORD', 'INTERMENSTRUAL_BLEEDING_RECORD', 'LEAN_BODY_MASS_RECORD', 'MENSTRUATION_FLOW_RECORD', 'NUTRITION_RECORD', 'POWER_RECORD', 'RESPIRATORY_RATE_RECORD', 'RESTING_HEART_RATE_RECORD', 'SKIN_TEMPERATURE_RECORD', name='data_type_enum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_data_type'), 'raw_records', ['data_type'], unique=False)
    op.create_index(op.f('ix_raw_records_email'), 'raw_records', ['email'], unique=False)
    op.create_index(op.f('ix_raw_records_id'), 'raw_records', ['id'], unique=False)
    op.create_index(op.f('ix_raw_records_time'), 'raw_records', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_records_time'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_email'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_data_type'), table_name='raw_records')
    op.drop_table('raw_records')
    # ### end Alembic commands ###
