"""initial

Revision ID: f955535ef4a0
Revises: 
Create Date: 2025-06-06 09:33:07.497883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f955535ef4a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_records_email'), 'rating_records', ['email'], unique=False)
    op.create_index(op.f('ix_rating_records_id'), 'rating_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_records_id'), table_name='rating_records')
    op.drop_index(op.f('ix_rating_records_email'), table_name='rating_records')
    op.drop_table('rating_records')
    # ### end Alembic commands ###
