apiVersion: v1
kind: Service
metadata:
  name: ratings-api
  namespace: hse-coursework-health
spec:
  selector:
    app: ratings-api
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: ClusterIP